language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t ngochieu276/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ngochieu276/react-test npm test -- --coverage

after_success:
  - docker build -t ngochieu276/multi-client ./client
  - docker build -t ngochieu276/multi-nginx ./nginx
  - docker build -t ngochieu276/multi-server ./server
  - docker build -t ngochieu276/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push ngochieu276/multi-client
  - docker push ngochieu276/multi-nginx
  - docker push ngochieu276/multi-server
  - docker push ngochieu276/multi-worker